### ISSUE TITLE
What is going on with the CSL file?

### ISSUE THREAD

**Issue by SimonGoring** [SimonGoring/neotoma_paper#39]
I edited it so that it would include version numbers for packages, and that seemed to work okay (commit https://github.com/SimonGoring/neotoma_paper/commit/0c3770f730b384c0d46e05bcfda8fc485ca57cf1#diff-23c87d0204a084e383b8043d0f2f8be7).  But I had to go back because the author lists got truncated by 'et al.' Using the visual editor provided by both Zotero and Mendeley the file should work okay, and give a full author list, but in practice this change (https://github.com/SimonGoring/neotoma_paper/commit/c1eb65ffdde671b2106ac7871d64f0e0f0456f15#diff-23c87d0204a084e383b8043d0f2f8be7) just removes all the author names and includes ony et al.  Any thoughts @karthik or @gavinsimpson ?

**Comment by gavinsimpson** [comment]
Have you tried this in some other workflow? I only ask because at the moment my blog use Pandoc but it is currently processed on an older version of Pandoc available with Fedora 19. It adds et al to everything when it processes the files, and I haven't changed the CSL at all from the one I download from the Zotero Github site.

I know this is not the same issue (you are seeing no authors only et al, I'm seeing all authors *and* et al, even if there is but one author) but it would be useful to rule out Pandoc as the cause when you are building.

What other software uses CSL that you or one of us might try quickly?

Have you dropped in a different CSL to see if that "rectifies" the situation temporarily?

**Comment by SimonGoring** [comment]
Fixed by starting with a different csl template and then editing it.  Resolved by commit a258f4a4eeabcde114f0a62e261c805091f1ffbb.
